name: 'Deploy'
description: 'Deploy a branch'
inputs:
  site:
    description: 'The site to deploy'
    required: true
    default: acm
  branch:
    description: 'The branch to deploy'
    required: true
    default: 'master'
  environ:
    description: 'The environment to deploy to'
    required: true
    default: 'review'
  command:
    description: 'deploy or destroy'
    required: true
    default: 'deploy'
  token:
    description: 'Hubot auth token'
    required: true
  url:
    description: 'Hubot url'
    required: true
outputs:
  status:
    description: 'The http status we got'
runs:
  using: 'node12'
  main: 'dist/index.js'